// import React from 'react'

export default [
  {
    id: 1,
    category: 'Картофель',
    title: 'Картофель Беллароза',
    img: require('assets/Mock/PopularItems/potato1.png'),
    seller: { rating: 5 },
    price: 250,
    priceMarker: 'medium',
    favorite: true,
  },
  {
    id: 2,
    category: 'Картофель',
    title: 'Картофель Адретта',
    img: require('assets/Mock/PopularItems/potato2.png'),
    seller: { rating: 4.3 },
    price: 300,
    priceMarker: 'low',
    favorite: true,
  },
  {
    id: 3,
    category: 'Картофель',
    title: 'Картофель Гала',
    img: require('assets/Mock/PopularItems/potato3.png'),
    seller: { rating: 3.7 },
    price: 350,
    priceMarker: 'low',
    favorite: true,
  },
  {
    id: 4,
    category: 'Картофель',
    title: 'Картофель Джелли',
    img: require('assets/Mock/PopularItems/potato4.png'),
    seller: { rating: 1.5 },
    price: 235450,
    priceMarker: 'high',
    favorite: true,
  },
  {
    id: 5,
    category: 'Картофель',
    title: 'Картофель Беллароза',
    img: require('assets/Mock/PopularItems/potato1.png'),
    seller: { rating: 5 },
    price: 250,
    priceMarker: 'medium',
    favorite: true,
  },
  {
    id: 6,
    category: 'Картофель',
    title: 'Картофель Адретта',
    img: require('assets/Mock/PopularItems/potato2.png'),
    seller: { rating: 4.3 },
    price: 300,
    priceMarker: 'medium',
    favorite: true,
  },
  {
    id: 7,
    category: 'Картофель',
    title: 'Картофель Гала',
    img: require('assets/Mock/PopularItems/potato3.png'),
    seller: { rating: 3.7 },
    price: 350,
    priceMarker: 'medium',
    favorite: true,
  },
  {
    id: 8,
    category: 'Картофель',
    title: 'Картофель Джелли',
    img: require('assets/Mock/PopularItems/potato4.png'),
    seller: { rating: 1.5 },
    price: 235450,
    priceMarker: 'high',
    favorite: true,
  },
]
