export default [
  {
    id: 1,
    category: 'Картофель',
    title: 'Картофель Беллароза',
    img: require('assets/Mock/MyLots/potato.png'),
    price: 250,
    priceMarker: 'low',
    status: 'review',
    description: 'Хорошая картошка, домашняя',
    volMin: 15,
    volMax: 500,
    country: 'Казахстан',
    county: 'Алматинская',
    city: 'Алматы',
    locality: null,
    itemPhotos: [
      require('assets/Mock/MyLots/potato.png'),
      require('assets/Mock/MyLots/potato.png'),
    ],
    itemCertificates: [require('assets/Mock/MyLots/potato.png')],
    seller: {
      userName: 'Артем',
      userLastName: 'Макарович',
      userPhone: '+7-(747)-568-4638',
      rating: 4.5,
    },
  },
  {
    id: 2,
    category: 'Огурцы',
    title: 'Огурцы',
    img: require('assets/Mock/MyLots/cucumber.png'),
    price: 90,
    priceMarker: 'medium',
    status: 'review',
    description: 'Хороший огурцы с грядка',
    volMin: 5,
    volMax: 50,
    country: 'Казахстан',
    county: 'Алматинская',
    city: 'Алматы',
    locality: null,
    itemPhotos: [
      require('assets/Mock/MyLots/cucumber.png'),
      require('assets/Mock/MyLots/cucumber.png'),
      require('assets/Mock/MyLots/cucumber.png'),
    ],
    itemCertificates: [require('assets/Mock/MyLots/cucumber.png')],
    seller: {
      userName: 'Артем',
      userLastName: 'Макарович',
      userPhone: '+7-(747)-568-4638',
      rating: 4.5,
    },
  },
  {
    id: 3,
    category: 'Томат',
    title: 'Томаты (помидоры)',
    img: require('assets/Mock/MyLots/tomatoes.png'),
    price: 320,
    priceMarker: 'low',
    status: 'active',
    description:
      'Помидоры прям с грядки. Снимаем после вашего заказа, все свежее и натуральное',
    volMin: 50,
    volMax: 500,
    country: 'Казахстан',
    county: 'Алматинская',
    city: 'Алматы',
    locality: null,
    itemPhotos: [
      require('assets/Mock/MyLots/tomatoes.png'),
      require('assets/Mock/MyLots/tomatoes.png'),
      require('assets/Mock/MyLots/tomatoes.png'),
      require('assets/Mock/MyLots/tomatoes.png'),
    ],
    itemCertificates: [require('assets/Mock/MyLots/tomatoes.png')],
    seller: {
      userName: 'Артем',
      userLastName: 'Макарович',
      userPhone: '+7-(747)-568-4638',
      rating: 4.5,
    },
  },
  {
    id: 4,
    category: 'Мясо',
    title: 'Говядина свежая',
    img: require('assets/Mock/MyLots/meat.png'),
    price: 1999,
    priceMarker: 'high',
    status: 'denied',
    description:
      'Отличное мясо, всегда свежее. Забой не позже чем за сутки до поставки.',
    volMin: 100,
    volMax: 10000,
    country: 'Казахстан',
    county: 'Алматинская',
    city: 'Алматы',
    locality: null,
    itemPhotos: [
      require('assets/Mock/MyLots/meat.png'),
      require('assets/Mock/MyLots/meat.png'),
      require('assets/Mock/MyLots/meat.png'),
      require('assets/Mock/MyLots/meat.png'),
      require('assets/Mock/MyLots/meat.png'),
    ],
    itemCertificates: [require('assets/Mock/MyLots/meat.png')],
    seller: {
      userName: 'Артем',
      userLastName: 'Макарович',
      userPhone: '+7-(747)-568-4638',
      rating: 4.5,
    },
  },
]
