// import React from 'react'

export default [
  {
    id: 1,
    category: 'Картофель',
    title: 'Картофель Беллароза',
    img: require('assets/Mock/PopularItems/potato1.png'),
    fullImage: require('assets/Mock/PopularItems/mainCucumber.png'),
    price: 250,
    averagePrice: 225,
    priceMarker: 'medium',
    status: 'active',
    replyStatus: 'active',
    favorite: false,
    description: 'Хорошая картошка, домашняя',
    volMin: 15,
    volMax: 500,
    country: 'Казахстан',
    county: 'Алматинская',
    city: 'Алматы',
    locality: null,
    itemPhotos: [
      require('assets/Mock/MyLots/potato.png'),
      require('assets/Mock/MyLots/potato.png'),
    ],
    itemCertificates: [require('assets/Mock/MyLots/potato.png')],
    seller: {
      userName: 'Артем',
      userLastName: 'Макарович',
      userPhone: '+7 747 568-4638',
      rating: 4.5,
    },
  },
  {
    id: 2,
    category: 'Огурцы',
    title: 'Огурцы',
    img: require('assets/Mock/MyLots/cucumber.png'),
    fullImage: require('assets/Mock/PopularItems/mainCucumber.png'),
    price: 90,
    averagePrice: 100,
    priceMarker: 'medium',
    status: 'review',
    replyStatus: 'review',
    favorite: 'true',
    description: 'Хороший огурцы с грядка',
    volMin: 5,
    volMax: 50,
    country: 'Казахстан',
    county: 'Алматинская',
    city: 'Алматы',
    locality: null,
    itemPhotos: [
      require('assets/Mock/MyLots/cucumber.png'),
      require('assets/Mock/MyLots/cucumber.png'),
      require('assets/Mock/MyLots/cucumber.png'),
    ],
    itemCertificates: [require('assets/Mock/MyLots/cucumber.png')],
    seller: {
      userName: 'Артем',
      userLastName: 'Макарович',
      userPhone: '+7 747 568-4638',
      rating: 4.5,
    },
  },
  {
    id: 3,
    category: 'Томат',
    title: 'Томаты (помидоры)',
    img: require('assets/Mock/MyLots/tomatoes.png'),
    fullImage: require('assets/Mock/PopularItems/mainCucumber.png'),
    price: 320,
    averagePrice: 290,
    priceMarker: 'low',
    status: 'finished',
    replyStatus: 'finished',
    favorite: false,
    description:
      'Помидоры прям с грядки. Снимаем после вашего заказа, все свежее и натуральное',
    volMin: 50,
    volMax: 500,
    country: 'Казахстан',
    county: 'Алматинская',
    city: 'Алматы',
    locality: null,
    itemPhotos: [
      require('assets/Mock/MyLots/tomatoes.png'),
      require('assets/Mock/MyLots/tomatoes.png'),
      require('assets/Mock/MyLots/tomatoes.png'),
      require('assets/Mock/MyLots/tomatoes.png'),
    ],
    itemCertificates: [require('assets/Mock/MyLots/tomatoes.png')],
    seller: {
      userName: 'Артем',
      userLastName: 'Макарович',
      userPhone: '+7 747 568-46-38',
      rating: 4.5,
    },
  },
  {
    id: 4,
    category: 'Мясо',
    title: 'Говядина свежая',
    img: require('assets/Mock/MyLots/meat.png'),
    fullImage: require('assets/Mock/PopularItems/mainCucumber.png'),
    price: 1999,
    averagePrice: 1790,
    priceMarker: 'high',
    status: 'denied',
    replyStatus: 'denied',
    favorite: false,
    description:
      'Отличное мясо, всегда свежее. Забой не позже чем за сутки до поставки.',
    volMin: 100,
    volMax: 10000,
    country: 'Казахстан',
    county: 'Алматинская',
    city: 'Алматы',
    locality: null,
    itemPhotos: [
      require('assets/Mock/MyLots/meat.png'),
      require('assets/Mock/MyLots/meat.png'),
      require('assets/Mock/MyLots/meat.png'),
      require('assets/Mock/MyLots/meat.png'),
      require('assets/Mock/MyLots/meat.png'),
    ],
    itemCertificates: [require('assets/Mock/MyLots/meat.png')],
    seller: {
      userName: 'Артем',
      userLastName: 'Макарович',
      userPhone: '+7 747 568-4638',
      rating: 4.5,
    },
  },
  {
    id: 5,
    category: 'Картофель',
    title: 'Картофель Морской',
    img: require('assets/Mock/PopularItems/potato1.png'),
    fullImage: require('assets/Mock/PopularItems/mainCucumber.png'),
    price: 375,
    averagePrice: 225,
    priceMarker: 'medium',
    status: 'active',
    replyStatus: 'active',
    favorite: false,
    description: 'Хорошая картошка, домашняя',
    volMin: 100,
    volMax: 1000,
    country: 'Казахстан',
    county: 'Алматинская',
    city: 'Алматы',
    locality: null,
    itemPhotos: [
      require('assets/Mock/MyLots/potato.png'),
      require('assets/Mock/MyLots/potato.png'),
    ],
    itemCertificates: [require('assets/Mock/MyLots/potato.png')],
    seller: {
      userName: 'Артем',
      userLastName: 'Макарович',
      userPhone: '+7 747 568-4638',
      rating: 4.5,
    },
  },
  {
    id: 6,
    category: 'Огурцы',
    title: 'Огурцы дачные',
    img: require('assets/Mock/MyLots/cucumber.png'),
    fullImage: require('assets/Mock/PopularItems/mainCucumber.png'),
    price: 110,
    averagePrice: 100,
    priceMarker: 'medium',
    status: 'review',
    replyStatus: 'review',
    favorite: 'true',
    description: 'Хороший огурцы с грядка',
    volMin: 10,
    volMax: 100,
    country: 'Казахстан',
    county: 'Алматинская',
    city: 'Алматы',
    locality: null,
    itemPhotos: [
      require('assets/Mock/MyLots/cucumber.png'),
      require('assets/Mock/MyLots/cucumber.png'),
      require('assets/Mock/MyLots/cucumber.png'),
    ],
    itemCertificates: [require('assets/Mock/MyLots/cucumber.png')],
    seller: {
      userName: 'Артем',
      userLastName: 'Макарович',
      userPhone: '+7 747 568-4638',
      rating: 4.5,
    },
  },
]
