import React from 'react'
import {
  Cereals,
  CoffeeTea,
  CompoundFeed,
  LifeStock,
  Dairy,
  Eggs,
  FlourMalt,
  Fruits,
  Honney,
  Meat,
  Nuts,
  OilFat,
  OilSeeds,
  SeaFood,
  TreesPlants,
  Veggies,
} from 'assets/Products'
import I18n from 'I18n'

export default [
  {
    id: 1,
    icon: () => <LifeStock />,
    text: () => `${I18n.t('Categories.animals')}`,
    bgColor: '#FFF4DE',
    textColor: '#FC9720',
  },
  {
    id: 2,
    icon: () => <Meat />,
    text: () => `${I18n.t('Categories.meat')}`,
    bgColor: '#FFF0E8',
    textColor: '#FF6F41',
  },
  {
    id: 3,
    icon: () => <Veggies />,
    text: () => `${I18n.t('Categories.veggies')}`,
    bgColor: '#FFF0E8',
    textColor: '#FF9F69',
  },
  {
    id: 4,
    icon: () => <Fruits />,
    text: () => `${I18n.t('Categories.fruits')}`,
    bgColor: '#EAFFF2',
    textColor: '#00A944',
  },
  {
    id: 5,
    icon: () => <TreesPlants />,
    text: () => `${I18n.t('Categories.treesPlants')}`,
    bgColor: '#E6FFE2',
    textColor: '#128100',
  },
  {
    id: 6,
    icon: () => <OilFat />,
    text: () => `${I18n.t('Categories.oilFats')}`,
    bgColor: '#FFFBEE',
    textColor: '#DD9F00',
  },
  {
    id: 7,
    icon: () => <FlourMalt />,
    text: () => `${I18n.t('Categories.flourMalt')}`,
    bgColor: '#FFF4EA',
    textColor: '#856F5C',
  },
  {
    id: 8,
    icon: () => <Cereals />,
    text: () => `${I18n.t('Categories.cereals')}`,
    bgColor: '#FFF8ED',
    textColor: '#F49300',
  },
  {
    id: 9,
    icon: () => <CompoundFeed />,
    text: () => `${I18n.t('Categories.compoundFeed')}`,
    bgColor: '#FCF9FF',
    textColor: '#7D6798',
  },
  {
    id: 10,
    icon: () => <CoffeeTea />,
    text: () => `${I18n.t('Categories.coffeeTea')}`,
    bgColor: '#FFEFDD',
    textColor: '#6A381F',
  },
  {
    id: 11,
    icon: () => <OilSeeds />,
    text: () => `${I18n.t('Categories.oilSeeds')}`,
    bgColor: '#FFF9E8',
    textColor: '#D19D00',
  },
  {
    id: 12,
    icon: () => <Dairy />,
    text: () => `${I18n.t('Categories.dairy')}`,
    bgColor: '#EEFAFF',
    textColor: '#009FE3',
  },
  {
    id: 13,
    icon: () => <Nuts />,
    text: () => `${I18n.t('Categories.nuts')}`,
    bgColor: '#FFE9D4',
    textColor: '#BC5A00',
  },
  {
    id: 14,
    icon: () => <SeaFood />,
    text: () => `${I18n.t('Categories.seafood')}`,
    bgColor: '#E4F2FF',
    textColor: '#0078E7',
  },
  {
    id: 15,
    icon: () => <Honney />,
    text: () => `${I18n.t('Categories.honey')}`,
    bgColor: '#FFFBEF',
    textColor: '#E7A600',
  },
  {
    id: 16,
    icon: () => <Eggs />,
    text: () => `${I18n.t('Categories.eggs')}`,
    bgColor: '#ECF7FF',
    textColor: '#0094FF',
  },
]
